### PR TITLE
Use Doctum instead of Sami

### PR DESCRIPTION
**Pull request by williamdes**
Use Doctum instead of Sami

https://github.com/code-lts/doctum#readme

### CODE REVIEW

**Comment by williamdes** [comment]
```
williamdes@williamdes:/mnt/Dev/@code-lts/bolt-api-docs$ php vendor/bin/doctum.php update config.php -v --force
 Updating project 

Version master
  Parsing   done
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Configuration\Content\FieldType::__construct" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/Content/FieldType.php:14
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Configuration\Parser\ContentTypesParser::parseContentType" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/Parser/ContentTypesParser.php:64
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Configuration\Parser\GeneralParser::parseConnectionParams" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/Parser/GeneralParser.php:215
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Configuration\PathResolver::__construct" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/PathResolver.php:52
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Configuration\PathResolver::resolve" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/PathResolver.php:98
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Configuration\Config::get" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Configuration/Config.php:160
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Controller\TwigAwareController::render" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Controller/TwigAwareController.php:77
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Controller\Frontend\DetailController::record" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Controller/Frontend/DetailController.php:42
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Twig\JsonExtension::normalizeRecords" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/JsonExtension.php:62
ERROR: "6" @param tags are expected but only "2" found on "Bolt\Twig\Node\SetcontentNode::__construct" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/Node/SetcontentNode.php:27
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Twig\ImageExtension::showImage" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/ImageExtension.php:89
ERROR: "6" @param tags are expected but only "1" found on "Bolt\Twig\ImageExtension::thumbnail" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/ImageExtension.php:107
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Twig\LocaleExtension::localedatetime" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/LocaleExtension.php:129
ERROR: "4" @param tags are expected but only "2" found on "Bolt\Twig\ContentExtension::getExcerpt" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/ContentExtension.php:244
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Twig\ContentExtension::getLink" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Twig/ContentExtension.php:349
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Storage\ContentQueryParser::setParameter" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Storage/ContentQueryParser.php:157
ERROR: "2" @param tags are expected but only "1" found on "Bolt\Storage\ContentQueryParser::setDirective" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Storage/ContentQueryParser.php:360
ERROR: "3" @param tags are expected but only "1" found on "Bolt\Storage\QueryParameterParser::defaultFilterHandler" in /mnt/Dev/@code-lts/bolt-api-docs/core/src/Storage/QueryParameterParser.php:250

  Rendering done

 Version    Updated C    Removed C 
   master          256            0

 Version    Updated C    Updated N    Removed C    Removed N 
   master          256           40            0            0

```

:green_circle: :rocket: Ready to go :)

**Comment by bobdenotter** [comment]
Thank you, @williamdes 

I'll check it out, and if it doesn't break we'll happily use Doctum instead of Sami going forward! 👍

**Comment by williamdes** [comment]
> Thank you, @williamdes
> 
> I'll check it out, and if it doesn't break we'll happily use Doctum instead of Sami going forward!

Happy to bring back support for abandoned code ;) :muscle:

**Review by bobdenotter — APPROVED** [review]
@williamdes Doctum works like a charm! Thank you for your work on this! 👍

**Comment by williamdes** [comment]
> @williamdes Doctum works like a charm! Thank you for your work on this!

Thank you for your nice comments !
Waiting patiently to see the documentation generated online :p

**Comment by bobdenotter** [comment]
I've just deployed the updated docs: https://api-docs.boltcms.io/

**Comment by williamdes** [comment]
> I've just deployed the updated docs: https://api-docs.boltcms.io/

I just tested and 
https://github.com/bolt/api-docs/blob/f595a48e0a21547b0c172c780e15d9220cf2adb1/config.php#L24

seems to be badly configured (example: https://api-docs.boltcms.io/master/Bolt/Command/ClearThumbnailCacheCommand.html)

I deleted my fork so I can not make a PR very easily, maye you can have a look at this error.
`api-docs/core/` seems to be what needs to be removed for the GitHub URLs to work

**Comment by bobdenotter** [comment]
> seems to be badly configured

Ah, I see.. Thanks! Fixed and redeployed.

**Comment by williamdes** [comment]
> > seems to be badly configured
> 
> Ah, I see.. Thanks! Fixed and redeployed.

Do not forget to push your commit :p

**Comment by bobdenotter** [comment]
Hah, caught me! 😅

**Comment by williamdes** [comment]
:thinking:  https://docs.bolt.cm/api/bolt/common/1.0/index.html seems to be using Sami, what can I do to fix this ?

**Comment by williamdes** [comment]
Hi @bobdenotter 

Could you please update the slogan for this repository to use "Doctum" and edit https://github.com/bolt/bolt/wiki/%5BRelease-Process%5D-Overview#introduction ?

Thank you ;)

**Comment by bobdenotter** [comment]
I've updated the repo description.. The "Release process" page is due for a major overhaul, as we'll be moving to `bolt/core` very soon, with the launch of Bolt 4.

**Pull request merged**
